#!/bin/sh
set -e
#
git checkout openshift-php && git pull
git checkout mdref && git pull
git checkout mdref-http && git pull
git checkout mdref-raphf && git pull
git checkout mdref-propro && git pull
git checkout mdref-pq && git pull
git checkout mdref-pq-gateway && git pull
#
git checkout master
git merge -s recursive -X subtree=.openshift/ -m "merge openshift-php" openshift-php
git merge -s recursive -X subtree=mdref/ -m "merge mdref" mdref
git merge -s recursive -X subtree=mdref/refs/http/ -m "merge mdref-http" mdref-http
git merge -s recursive -X subtree=mdref/refs/raphf/ -m "merge mdref-raphf" mdref-raphf
git merge -s recursive -X subtree=mdref/refs/propro/ -m "merge mdref-propro" mdref-propro
git merge -s recursive -X subtree=mdref/refs/pq/ -m "merge mdref-pq" mdref-pq
git merge -s recursive -X subtree=mdref/refs/pq-gateway/ -m "merge mdref-pq-gateway" mdref-pq-gateway
